# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-21 22:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': '\u5e93\u5b58\u8868'},
        ),
    ]
