# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-24 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0002_auto_20200623_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsid', models.PositiveIntegerField()),
                ('colorid', models.PositiveIntegerField()),
                ('sizeid', models.PositiveIntegerField()),
                ('count', models.PositiveIntegerField()),
                ('isdelete', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.UserInfo')),
            ],
            options={
                'verbose_name': '\u8d2d\u7269\u8f66\u8868',
            },
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set([('goodsid', 'colorid', 'sizeid')]),
        ),
    ]
