# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-26 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='\u5f85\u652f\u4ed8', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='trade_no',
            field=models.CharField(default='', max_length=120),
        ),
    ]
